# -*- coding: utf-8 -*-
"""Cartoonify.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U0YydFHAeYnW2o3k_Q2Z6tvZaMjnx9E6
"""

import cv2
import numpy as np
from google.colab.patches import cv2_imshow

img = cv2.imread('unionPic.jpg')

#edges
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
gray = cv2.medianBlur(gray, 5)
edges = cv2.adaptiveThreshold(gray, 255, cv2.ADAPTIVE_THRESH_MEAN_C, cv2.THRESH_BINARY, 9, 4)
#edges = cv2.Canny(img,60,100)

#color
color = cv2.bilateralFilter(img, 13, 300, 300)

#cartoon
cartoon = cv2.bitwise_and(color, color, mask=edges)

cv2_imshow(img)
cv2_imshow(color)
cv2_imshow(edges)
cv2_imshow(cartoon)
cv2.waitKey(0)
cv2.destroyAllWindows()